run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "internal/*"
      linters:
        - dupl
    - path: _test\.go
      linters:
        - errcheck
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - asasalint
    - containedctx
    # - contextcheck
    - durationcheck
    # - exhaustruct
    - gocheckcompilerdirectives
    - intrange
    - loggercheck
    - makezero
    - mirror
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tenv
    - testableexamples
    - thelper
    - usestdlibvars


linters-settings:
  revive:
    rules:
      - name: comment-spacings
