version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - containedctx
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: internal/*
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
