---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cf-tunnel-operator-walnuts-dev-cf-tunnel-operator-walnuts-dev-v1beta1-cloudflaretunnel
  failurePolicy: Fail
  name: mcloudflaretunnel-v1beta1.kb.io
  rules:
  - apiGroups:
    - cf-tunnel-operator.walnuts.dev.cf-tunnel-operator.walnuts.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudflaretunnels
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cf-tunnel-operator-walnuts-dev-cf-tunnel-operator-walnuts-dev-v1beta1-cloudflaretunnel
  failurePolicy: Fail
  name: vcloudflaretunnel-v1beta1.kb.io
  rules:
  - apiGroups:
    - cf-tunnel-operator.walnuts.dev.cf-tunnel-operator.walnuts.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudflaretunnels
  sideEffects: None
