## Append samples of your project ##
resources:
- cf-tunnel-operator.walnuts.dev_v1beta1_cloudflaretunnel.yaml
- cf-tunnel-operator.walnuts.dev_v1beta1_clustercloudflaretunnel.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
