apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel-operator-system
resources:
- ../default
- secret.yaml
patches:
- path: manager.yaml
secretGenerator:
- name: cloudflare-secrets
  behavior: merge
  envs:
  - .env
