apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
patches:
- path: manager.yaml
secretGenerator:
- name: cloudflare-secrets
  namespace: system
  behavior: replace
  envs:
  - .env
