apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudflare-tunnel-operator.fullname" . }}-manager-role
  labels:
  {{- include "cloudflare-tunnel-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf-tunnel-operator.walnuts.dev
  resources:
  - cloudflaretunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf-tunnel-operator.walnuts.dev
  resources:
  - cloudflaretunnels/finalizers
  verbs:
  - update
- apiGroups:
  - cf-tunnel-operator.walnuts.dev
  resources:
  - cloudflaretunnels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflare-tunnel-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "cloudflare-tunnel-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cloudflare-tunnel-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cloudflare-tunnel-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
