{{- if not .Values.cloudflareToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel-operator.token-secret.name" . }}
  labels:
  {{- include "cloudflare-tunnel-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
type: Opaque
data:
  cloudflareAPIToken: {{ .Values.cloudflareToken.cloudflareAPIToken | b64enc | quote }}
{{- end }}
